### ISSUE TITLE
Not able to access it

### ISSUE THREAD

**Issue by aniariv** [toby/keypass#1]
Hi

I have the app for several years and since i uploaded the last version of ios i am not able to open it and does not show an update on the appstore. Please help i am desparate

**Comment by toby** [comment]
I think you may be talking about an iOS app with a similar name, this is a bash script for use on the command line.

**Comment by aniariv** [comment]
Hey

Yes, any idea how I can find the developer?

Thanks
Ania

**Comment by toby** [comment]
Sadly, no.

**Comment by aniariv** [comment]
Thanks
